### ISSUE TITLE
Notify via private message

### ISSUE THREAD

**Issue by Schoaf** [prabhu43/mattermost-spybot#2]
I think it's annoying to notify everyone in a channel just because one user wants a notification.

As suggested here (https://docs.mattermost.com/developer/webhooks-incoming.html) you should be able to use the incomming webhook but use @username as channel name to just send a private message as notification.

**Comment by prabhu43** [comment]
Hi @Schoaf 
Thanks for your suggestion. But It won't notify everyone. Bot uses a dedicated channel for this purpose and notifies only 2 persons: person who is being spied and person who is requesting to spy. 
This is how it will look like:
<img width="231" alt="screen shot 2017-11-17 at 10 33 17 pm" src="https://user-images.githubusercontent.com/1008923/32959460-b29fd432-cbe7-11e7-90fc-0e5a30701169.png">


Correct me if I am missing anything.

And the link that you shared is not working.

**Comment by Schoaf** [comment]
sure. But that means that everyone who wants to use the bot has to join the channel. So I either have to jump in and out of the one channel or I have to disable normal notifications for that channel.
Also, if a lot of users come online at 8 am, there is a lot of noise in the channel.

Sorry, I posted a wrong link. It is documented here: https://docs.mattermost.com/developer/webhooks-incoming.html under "Override a channel":

> To send a message to a direct message channel, add an “@” symbol followed by the username to the channel parameter.
> 
> `payload={"channel": "@username", "text": "Hello, this is some text\nThis is more text. :tada:"}`
>

**Comment by prabhu43** [comment]
@Schoaf I tried doing so. It looks like each user should have incoming webhook. 
1. I created an incoming webhook as UserA.
2. Assume UserA spies on UserB. Now posting a message using this webhook id with payload {"channel": "@userB", "text": "hello"}
3. Now UserA and UserB can see this message.

If UserC spies on UserB, i have to use another incoming webhook created by UserC. 

Is this what you suggest?

**Comment by Schoaf** [comment]
Actually no.
I believe the webhook does not have to be from any user involved. That has nothing to do with it.
So I'd say:
1. Create a webhook as any user. maybe the admin.
2. Assume User A spies on UserB. Post a message as username="SpyBot" to "channel": "@userb", "text": "UserA just got online."
3. Now only UserA can see the message, as there is no actual SpyBot user.
4. UserA can just remove the useless conversation from the sidebar.

I'm not sure if that really works, but as far as I understand the documentation it should. Maybe you have to create an actual user for SpyBot though. But usually an incomming webhook can post into any channel.

**Comment by prabhu43** [comment]
@Schoaf Changed the approach to use direct channel instead of public channel. Closing this issue.
Thanks!

**Comment by Schoaf** [comment]
Great! I'll try it out as soon as possible. 👍
