### ISSUE TITLE
Use slash command instead of outgoing webhook

### ISSUE THREAD

**Issue by Schoaf** [prabhu43/mattermost-spybot#3]
The benefits of slash-commands:

- Slash commands work in all channels.
- They can have additional descriptions which makes it easier to use
- they are listed so someone could look up the possible commands and dont have to remember it.
- They can post an ephemeral message back to tell the user, that the action has successfully been placed.

**Comment by prabhutw** [comment]
@Schoaf Thanks for your inputs. 
Replaced outgoing webhook with slash command. So closing this issue!

**Comment by prabhu43** [comment]
@Schoaf Thanks for your inputs!
Replaced outgoing webhook with slash command. So closing this issue.

**Comment by Schoaf** [comment]
Thank man. Really nice feature!
