### ISSUE TITLE
Any plans to release / update

### ISSUE THREAD

**Issue by uhlhosting** [prabhu43/mattermost-spybot#6]

**Comment by prabhu43** [comment]
@uhlhosting What feature/fix you are expecting to be released?

**Comment by uhlhosting** [comment]
Mattermost has changed a bit the way they install plugins, I would like to see an official wrap around the current Mattermost changes.

**Comment by uhlhosting** [comment]
Also the option to list users spied, to /unspy maybe?

**Comment by prabhu43** [comment]
@uhlhosting Can you check [mattermost-plugin-spybot](https://github.com/scottleedavis/mattermost-plugin-spybot)? @scottleedavis had created a plugin for mattermost-spybot

**Comment by uhlhosting** [comment]
I already did, in that case was thinking maybe the 2 of you can make from 2 one better. ? 💯

**Comment by scottleedavis** [comment]
Just recently added /spy list.

**Comment by scottleedavis** [comment]
Happy to collaborate on making the plugin better. :)

**Comment by prabhu43** [comment]
@scottleedavis @uhlhosting Do you want to rewrite this repo to work with new mattermost?

**Comment by scottleedavis** [comment]
I am happy with working on the plugin vs. this integration.  :)

**Comment by prabhu43** [comment]
Yes @scottleedavis. I am also thinking the same. Let me know how can we make the plugin [mattermost-plugin-spybot](https://github.com/scottleedavis/mattermost-plugin-spybot) better. And I will archive this repository.

**Comment by scottleedavis** [comment]
@prabhu43 I have added you as a collaborator on the repo.  You are welcome to contribute anytime.  :)
